Config = Config or {}

Config.UsingDefaultQBApartments = true
Config.OnlyShowOnDuty = true
Config.UseCQCMugshot = true

-- Front, Back Side. Use 4 for both sides, we recommend leaving at 1 for default.
Config.MugPhotos = 1

-- Images for mug shots will be uploaded here. Add a Discord webhook. 
Config.MugShotWebhook = ''

-- Clock-in notifications for duty. Add a Discord webhook.
-- Command /mdtleaderboard, will display top players per clock-in hours.
Config.ClockinWebhook = ''

-- If set to true = Fine gets automatically removed from bank automatically charging the player.
-- If set to false = The fine gets sent as an Invoice to their phone and it us to the player to pay for it, can remain unpaid and ignored.
Config.BillVariation = true

-- Set up your inventory to automatically retrieve images when a weapon is registered at a weapon shop or self-registered.
-- If you're utilizing lj-inventory's latest version from GitHub, no further modifications are necessary. 
-- However, if you're using a different inventory system, please refer to the "Inventory Edit | Automatic Add Weapons with images" section in ps-mdt's README.
Config.InventoryForWeaponsImages = "lj-inventory"

-- "LegacyFuel", "lj-fuel", "ps-fuel"
Config.Fuel = "ps-fuel"

-- Google Docs Link
Config.sopLink = {
    ['police'] = '',
    ['ambulance'] = '',
    ['bcso'] = '',
    ['doj'] = '',
    ['sast'] = '',
    ['sasp'] = '',
    ['doc'] = '',
    ['lssd'] = '',
    ['sapr'] = '',
}

-- Google Docs Link
Config.RosterLink = {
    ['police'] = '',
    ['ambulance'] = '',
    ['bcso'] = '',
    ['doj'] = '',
    ['sast'] = '',
    ['sasp'] = '',
    ['doc'] = '',
    ['lssd'] = '',
    ['sapr'] = '',	
}

Config.PoliceJobs = {
    ['police'] = true,
    ['lspd'] = true,
    ['bcso'] = true,
    ['sast'] = true,
    ['sasp'] = true,
    ['doc'] = true,
    ['lssd'] = true,
    ['sapr'] = true,
    ['pa'] = true
}

Config.AmbulanceJobs = {
    ['ambulance'] = true,
    ['doctor'] = true
}

Config.DojJobs = {
    ['lawyer'] = true,
    ['judge'] = true
}

-- This is a workaround solution because the qb-menu present in qb-policejob fills in an impound location and sends it to the event. 
-- If the impound locations are modified in qb-policejob, the changes must also be implemented here to ensure consistency.

Config.ImpoundLocations = {
    [1] = vector4(436.68, -1007.42, 27.32, 180.0),
    [2] = vector4(-436.14, 5982.63, 31.34, 136.0),
}

-- Support for Wraith ARS 2X. 

Config.UseWolfknightRadar = false
Config.WolfknightNotifyTime = 5000 -- How long the notification displays for in milliseconds (30000 = 30 seconds)

-- IMPORTANT: To avoid making excessive database queries, modify this config to true 'CONFIG.use_sonorancad = true' setting in the configuration file located at 'wk_wars2x/config.lua'. 
-- Enabling this setting will limit plate checks to only those vehicles that have been used by a player.

Config.LogPerms = {
	['ambulance'] = {
		[4] = true,
	},
	['police'] = {
		[4] = true,
	},
    ['bcso'] = {
		[4] = true,
	},
    ['sast'] = {
		[4] = true,
	},
    ['sasp'] = {
		[4] = true,
	},
    ['sapr'] = {
		[4] = true,
	},
    ['doc'] = {
		[4] = true,
	},
    ['lssd'] = {
		[4] = true,
	},
}

Config.PenalCodeTitles = {
    [1] = 'OFFENSES AGAINST PERSONS',
    [2] = 'OFFENSES INVOLVING THEFT',
    [3] = 'OFFENSES INVOLVING FRAUD',
    [4] = 'OFFENSES INVOLVING DAMAGE TO PROPERTY',
    [5] = 'OFFENSES AGAINST PUBLIC ADMINISTRATION',
    [6] = 'OFFENSES AGAINST PUBLIC ORDER',
    [7] = 'OFFENSES AGAINST HEALTH AND MORALS',
    [8] = 'OFFENSES AGAINST PUBLIC SAFETY',
    [9] = 'OFFENSES INVOLVING THE OPERATION OF A VEHICLE',
    [10] = 'OFFENSES INVOLVING THE WELL-BEING OF WILDLIFE',
}

Config.PenalCode = {
    [1] = {
        [1] = {title = 'Vold', class = 'Forbrydelser', id = 'P.C. 1001', months = 10, fine = 2500, color = 'orange'},
        [2] = {title = 'Grov vold', class = 'Forbrydelse', id = 'P.C. 1002', months = 15, fine = 3500, color = 'orange'},
        [3] = {title = 'Vold mod tjenstemand', class = 'Forbrydelse', id = 'P.C. 1003', months = 20, fine = 4000, color = 'orange'},
        [4] = {title = 'Grov vold mod tjeneste mand', class = 'Forbrydelse', id = 'P.C. 1004', months = 30, fine = 5000, color = 'red'},
        [5] = {title = 'Uagtsomt manddrab', class = 'Forbrydelse', id = 'P.C. 1005', months = 45, fine = 4500, color = 'red'},
        [6] = {title = 'Uagtsomt mandrab I køretøj', class = 'Forbrydelse', id = 'P.C. 1006', months = 55, fine = 5000, color = 'red'},
        [7] = {title = 'Mordforsøg på civile', class = 'Forbrydelse', id = 'P.C. 1007', months = 50, fine = 7200, color = 'red'},
        [8] = {title = 'Andengradsmord', class = 'Forbrydelse', id = 'P.C. 1008', months = 70, fine = 10000, color = 'red'},
        [9] = {title = 'Medvirkene til andengradsmord', class = 'Forbrydelse', id = 'P.C. 1009', months = 60, fine = 9500, color = 'red'},
        [10] = {title = 'Førstegradsmord', class = 'Forbrydelse', id = 'P.C. 1010', months = 100, fine = 15000, color = 'red'},
        [11] = {title = 'Medvirkene til førstegradsmord', class = 'Forbrydelse', id = 'P.C. 1011', months = 90, fine = 13500, color = 'red'},
        [12] = {title = 'Mord på tjenestemand', class = 'Forbrydelse', id = 'P.C. 1012', months = 120, fine = 20000, color = 'red'},
        [13] = {title = 'Mordforsøg på tjenestemand', class = 'Forbrydelse', id = 'P.C. 1013', months = 70, fine = 12000, color = 'red'},
        [14] = {title = 'Medvirkene til mord på tjenestemand', class = 'Forbrydelse', id = 'P.C. 1014', months = 110, fine = 19000, color = 'red'},
        [15] = {title = 'Forstyrelse af politiet´s arbejde', class = 'Forbrydelse', id = 'P.C. 1015', months = 10, fine = 600, color = 'green'},
        [16] = {title = 'Kidnapning', class = 'Forbrydelse', id = 'P.C. 1016', months = 22, fine = 3000, color = 'orange'},
        [17] = {title = 'Medvirkene til kidnapning', class = 'Forbrydelse', id = 'P.C. 1017', months = 15, fine = 1500, color = 'orange'},
        [18] = {title = 'Forsøg på kidnapning', class = 'Forbrydelse', id = 'P.C. 1018', months = 10, fine = 750, color = 'orange'},
        [19] = {title = 'Gidseltagning', class = 'Forbrydelse', id = 'P.C. 1019', months = 30, fine = 4000, color = 'orange'},
        [20] = {title = 'Medvirkene til gidseltagning', class = 'Forbrydelse', id = 'P.C. 1020', months = 25, fine = 3600, color = 'orange'},
        [21] = {title = 'Forhindre fængsling', class = 'Forbrydelse', id = 'P.C. 1021', months = 25, fine = 4000, color = 'orange'},
        [22] = {title = 'Trusler', class = 'Forbrydelse', id = 'P.C. 1022', months = 10, fine = 950, color = 'orange'},
        [23] = {title = 'Hensynsløs adfærd', class = 'Forbrydelse', id = 'P.C. 1023', months = 10, fine = 1000, color = 'orange'},
        [24] = {title = 'Banderelateret skyderi', class = 'Forbrydelse', id = 'P.C. 1024', months = 45, fine = 4550, color = 'red'},
        [25] = {title = 'Kannibalisme', class = 'Forbrydelse', id = 'P.C. 1025', months = 105, fine = 19000, color = 'red'},
        [26] = {title = 'Torture', class = 'Forbrydelse', id = 'P.C. 1026', months = 25, fine = 4500, color = 'red'},
    },
    [2] = {
        [1] = {title = 'Brugstyveri', class = 'Forbrydelse', id = 'P.C. 2001', months = 10, fine = 2500, color = 'orange'},
        [2] = {title = 'Biltyveri', class = 'Forbrydelse', id = 'P.C. 2002', months = 12, fine = 2500, color = 'orange'},
        [3] = {title = 'Indbrud', class = 'Forbrydelse', id = 'P.C. 2004', months = 15, fine = 3300, color = 'orange'},
        [4] = {title = 'Bankrøveri', class = 'Forbrydelse', id = 'P.C. 2005', months = 35, fine = 4000, color = 'red'},
        [5] = {title = 'Butiksrøveri', class = 'Forbrydelse', id = 'P.C. 2006', months = 20, fine = 3400, color = 'orange'},
        [6] = {title = 'Juvelrøveri', class = 'Forbrydelse', id = 'P.C. 2007', months = 35, fine = 4000, color = 'red'},
        [7] = {title = 'National bankrøveri', class = 'Forbrydelse', id = 'P.C. 2019', months = 45, fine = 5000, color = 'red'},
        [8] = {title = 'ATM røveri', class = 'Forbrydelse', id = 'P.C. 2019', months = 10, fine = 1250, color = 'red'},
        [9] = {title = 'Røveri', class = 'Forbrydelse', id = 'P.C. 2008', months = 20, fine = 3350, color = 'orange'},
        [10] = {title = 'Røveri forsøg', class = 'Forbrydelse', id = 'P.C. 2012', months = 15, fine = 1500, color = 'orange'},
        [11] = {title = 'Betaler ikke regning', class = 'Overtrædelse', id = 'P.C. 2014', months = 0, fine = 1350, color = 'green'},
        [12] = {title = 'Besiddelse af ulovlig skaffet penge', class = 'Forbrydelse', id = 'P.C. 2015', months = 10, fine = 1050, color = 'orange'},
        [13] = {title = 'Besiddelse af statsejet genstande', class = 'Forbrydelse', id = 'P.C. 2016', months = 15, fine = 1250, color = 'orange'},
        [14] = {title = 'Besiddelse af ting brugt i kriminelle sammenhæng', class = 'Forbrydelse', id = 'P.C. 2017', months = 12, fine = 1250, color = 'orange'},
        [15] = {title = 'Salg af genstande brugte til kriminalitet', class = 'Forbrydelse', id = 'P.C. 2018', months = 15, fine = 1300, color = 'orange'},
        [16] = {title = 'Tyveri af luft køretøj', class = 'Forbrydelse', id = 'P.C. 2019', months = 15, fine = 2350, color = 'orange'},
    },
    [3] = {
        [1] = {title = 'Udgiver sig for at være en anden civil', class = 'Forbrydelse', id = 'P.C. 3001', months = 5, fine = 1250, color = 'orange'},
        [2] = {title = 'Udgiver sig for at være tjenestemand', class = 'Forbrydelse', id = 'P.C. 3002', months = 15, fine = 1500, color = 'orange'},
        [3] = {title = 'Udgiver sig for at være en dommer', class = 'Forbrydelse', id = 'P.C. 3003', months = 20, fine = 1750, color = 'orange'},
        [4] = {title = 'Identitet tyveri på civil', class = 'Forbrydelse', id = 'P.C. 3004', months = 20, fine = 1500, color = 'orange'},
        [5] = {title = 'Identitet tyveri på tjenestemand', class = 'Forbrydelse', id = 'P.C. 3005', months = 15, fine = 3050, color = 'orange'},
        [6] = {title = 'Afpresning', class = 'Forbrydelse', id = 'P.C. 3006', months = 20, fine = 2000, color = 'orange'},
        [7] = {title = 'Svindel', class = 'Forbrydelse', id = 'P.C. 3007', months = 10, fine = 850, color = 'orange'},
        [8] = {title = 'Forfalskning', class = 'Forbrydelse', id = 'P.C. 3008', months = 15, fine = 1000, color = 'orange'},
        [9] = {title = 'Hvidvaskning', class = 'Forbrydelse', id = 'P.C. 3009', months = 20, fine = 2450, color = 'orange'},
    },
    [4] = {
        [1] = {title = 'Ulovlig indtrængelse', class = 'Forbrydelse', id = 'P.C. 4001', months = 15, fine = 1350, color = 'orange'},
        [2] = {title = 'Ulovlig indtrængelse på PD eller Pillbox', class = 'Forbrydelse', id = 'P.C. 4002', months = 25, fine = 3000, color = 'orange'},
        [3] = {title = 'Brandstiftelse', class = 'Forbrydelse', id = 'P.C. 4003', months = 20, fine = 1500, color = 'orange'},
        [4] = {title = 'Hærværk på', class = 'Overtrædelse', id = 'P.C. 4004', months = 0, fine = 950, color = 'green'},
        [5] = {title = 'Hærværk på PD eller Pillbox', class = 'Forbrydelse', id = 'P.C. 4005', months = 20, fine = 1500, color = 'orange'},
        [6] = {title = 'Miljøsvineri', class = 'Overtrædelse', id = 'P.C. 4006', months = 0, fine = 500, color = 'green'},
    },
    [5] = {
        [1] = {title = 'Bestikkelse', class = 'Forbrydelse', id = 'P.C. 5001', months = 5, fine = 2250, color = 'orange'},
        [2] = {title = 'Maske forbud', class = 'Overtrædelse', id = 'P.C. 5002', months = 0, fine = 750, color = 'green'},
        [3] = {title = 'Besiddelse af stjålene ting', class = 'Forbrydelse', id = 'P.C. 5004', months = 10, fine = 200, color = 'orange'},
        [4] = {title = 'Flugt', class = 'Forbrydelse', id = 'P.C. 5005', months = 10, fine = 2450, color = 'Orange'},
        [5] = {title = 'Flugt fra fængsel', class = 'Forbrydelse', id = 'P.C. 5006', months = 55, fine = 4000, color = 'red'},
        [6] = {title = 'Medvirkene til flugt fra fængsel', class = 'Forbrydelse', id = 'P.C. 5007', months = 45, fine = 2500, color = 'orange'},
        [7] = {title = 'Forsøg på flugt fra fængsel', class = 'Forbrydelse', id = 'P.C. 5008', months = 25, fine = 1500, color = 'orange'},
        [8] = {title = 'Brud på politi tilhold ', class = 'Forbrydelse', id = 'P.C. 5010', months = 5, fine = 1800, color = 'red'},
        [9] = {title = 'Misbrug af nødsystemer', class = 'Overtrædelse', id = 'P.C. 5013', months = 0, fine = 2300, color = 'green'},
        [10] = {title = 'Overtrædelse af retskendelse', class = 'Forbrydelse', id = 'P.C. 5015', months = 10, fine = 2950, color = 'orange'},
        [11] = {title = 'Forbliver væk fra retsag', class = 'Overtrædelse', id = 'P.C. 5016', months = 0, fine = 2650, color = 'green'},
        [12] = {title = 'Foragt', class = 'Forbrydelse', id = 'P.C. 5017', months = 0, fine = 1300, color = 'green'},
        [13] = {title = 'Modsætter anholdelse', class = 'Forbrydelse', id = 'P.C. 5018', months = 10, fine = 3150, color = 'orange'},
        [14] = {title = 'Besiddelse af PD medicin', class = 'Forbrydelse', id = 'P.C. 5018', months = 1, fine = 1200, color = 'orange'},
    },
    [6] = {
        [1] = {title = 'Adlyder ikke politiet´s anvisninger', class = 'Forbrydelse', id = 'P.C. 6001', months = 10, fine = 1450, color = 'orange'},
        [2] = {title = 'Gade uorden', class = 'Overtrædelse', id = 'P.C. 6002', months = 0, fine = 850, color = 'green'},
        [3] = {title = 'Falsk indberetning', class = 'Forbrydelse', id = 'P.C. 6004', months = 10, fine = 1850, color = 'orange'},
        [4] = {title = 'Chikane', class = 'Overtrædelse', id = 'P.C. 6005', months = 0, fine = 1950, color = 'green'},
        [5] = {title = 'Loitering på offenlig grund', class = 'Overtrædelse', id = 'P.C. 6009', months = 0, fine = 2000, color = 'green'},
        [6] = {title = 'Manglende Identitet', class = 'Overtrædelse', id = 'P.C. 6014', months = 0, fine = 1850, color = 'green'},
        [7] = {title = 'Korruption', class = 'Forbrydelse', id = 'P.C. 6017', months = 135, fine = 100000, color = 'red'},
        [8] = {title = 'Stalking', class = 'Forbrydelse', id = 'P.C. 6018', months = 10, fine = 1500, color = 'orange'},
    },
    [7] = {
         [1] = {title = 'Besiddelse af Heoin sprøjter', class = 'Forbrydelse', id = 'P.C. 7001', months = 0, fine = 0, color = 'orange'},
        [2] = {title = 'Besiddelse af heroin ingredienser', class = 'Forbrydelse', id = 'P.C. 7002', months = 0, fine = 0, color = 'orange'},
        [3] = {title = 'Besiddelse af LSD', class = 'Forbrydelse', id = 'P.C. 7003', months = 0, fine = 0, color = 'orange'},
        [4] = {title = 'Besiddelse af LSD ingredienser', class = 'Forbrydelse', id = 'P.C. 7004', months = 0, fine = 0, color = 'orange'},
        [5] = {title = 'Besiddelse af Meth', class = 'Forbrydelse', id = 'P.C. 7005', months = 0, fine = 0, color = 'orange'},
        [6] = {title = 'Besiddelse af Meth ingredienser', class = 'Forbrydelse', id = 'P.C. 7006', months = 0, fine = 0, color = 'orange'},
        [7] = {title = 'Besiddelse af oxy', class = 'Forbrydelse', id = 'P.C. 7007', months = 0, fine = 0, color = 'orange'},
        [8] = {title = 'Besiddelse af coke dukker', class = 'Forbrydelse', id = 'P.C. 7008', months = 0, fine = 4500, color = 'orange'},
        [9] = {title = 'Besiddelse af coke piller', class = 'Forbrydelse', id = 'P.C. 7009', months = 0, fine = 0, color = 'orange'},
        [10] = {title = 'Besiddelse af coke plader', class = 'Forbrydelse', id = 'P.C. 7010', months = 0, fine = 0, color = 'orange'},
        [11] = {title = 'Besiddelse af 100% meth', class = 'Forbrydelse', id = 'P.C. 7011', months = 0, fine = 0, color = 'orange'},
        [12] = {title = 'Besiddelse af 100% meth ingredienser', class = 'Forbrydelse', id = 'P.C. 7012', months = 0, fine = 0, color = 'orange'},
    },
    [8] = {
        [1] = {title = 'Ulovlig besiddelse af klasse A våben', class = 'Forbrydelse', id = 'P.C. 8001', months = 25, fine = 5200, color = 'red'},
        [2] = {title = 'Ulovlig besiddelse af klasse B våben', class = 'Forbrydelse', id = 'P.C. 8002', months = 45, fine = 7500, color = 'red'},
        [3] = {title = 'Ulovlig besiddelse af klasse C våben', class = 'Forbrydelse', id = 'P.C. 8003', months = 55, fine = 10000, color = 'red'},
        [4] = {title = 'Ulovlig besiddelse af klasse D våben', class = 'Forbrydelse', id = 'P.C. 8004', months = 35, fine = 8000, color = 'red'},
        [5] = {title = 'Ulovlig salg af klasse A våben', class = 'Forbrydelse', id = 'P.C. 8005', months = 15, fine = 4500, color = 'orange'},
        [6] = {title = 'Ulovlig salg af klasse B våben', class = 'Forbrydelse', id = 'P.C. 8006', months = 20, fine = 5000, color = 'orange'},
        [7] = {title = 'Ulovlig salg af klasse C våben', class = 'Forbrydelse', id = 'P.C. 8007', months = 30, fine = 6500, color = 'orange'},
        [8] = {title = 'Ulovlig salg af klasse D våben', class = 'Forbrydelse', id = 'P.C. 8008', months = 25, fine = 5500, color = 'orange'},
        [9] = {title = 'Ulovlig brug af våben', class = 'Forbrydelse', id = 'P.C. 8009', months = 10, fine = 450, color = 'orange'},
        [10] = {title = 'Besiddelse af ulovlig våbenmodifikation', class = 'Forbrydelse', id = 'P.C. 8010', months = 10, fine = 1950, color = 'orange'},
        [11] = {title = 'Våben transport', class = 'Forbrydelse', id = 'P.C. 8011', months = 10, fine = 4500, color = 'red'},
        [12] = {title = 'Flyver I ulovlig luftrum', class = 'Forbrydelse', id = 'P.C. 8014', months = 15, fine = 1300, color = 'orange'},
        [13] = {title = 'Ulovlig brug af springstof', class = 'Forbrydelse', id = 'P.C. 8016', months = 35, fine = 11000, color = 'red'},
    },
    [9] = {
        [1] = {title = 'Køre under påvirket tilstand', class = 'Forbrydelse', id = 'P.C. 9001', months = 10, fine = 1300, color = 'orange'},
        [2] = {title = 'Undlader at trække til side for udrykningskøretøj', class = 'Overtrædelse', id = 'P.C. 9004', months = 0, fine = 1300, color = 'green'},
        [3] = {title = 'Mangel på servicering af køretøj', class = 'Overtrædelse', id = 'P.C. 9005', months = 0, fine = 900, color = 'green'},
        [4] = {title = 'Ikke funktionelt køretøj', class = 'Overtrædelse', id = 'P.C. 9006', months = 0, fine = 1100, color = 'green'},
        [5] = {title = 'Hasaderet kørelse', class = 'Forbrydelse', id = 'P.C. 9008', months = 10, fine = 1750, color = 'orange'},
        [7] = {title = '4.grad hastighedsoverskridelse', class = 'Overtrædelse', id = 'P.C. 9009', months = 0, fine = 750, color = 'green'},
        [8] = {title = '3.grad hastighedsoverskridelse', class = 'Overtrædelse', id = 'P.C. 9009', months = 0, fine = 1150, color = 'green'},
        [9] = {title = '2.grad hastighedsoverskridelse', class = 'Overtrædelse', id = 'P.C. 9009', months = 0, fine = 2200, color = 'green'},
        [10] = {title = '1.grad hastighedsoverskridelse ', class = 'Overtrædelse', id = 'P.C. 9009', months = 10, fine = 2500, color = 'green'},
        [11] = {title = 'Kørelse I fratagelse perioden', class = 'Overtrædelse', id = 'P.C. 9012', months = 0, fine = 500, color = 'green'},
        [12] = {title = 'Ingen kørekort under kørelse = 'Overtrædelse', id = 'P.C. 9013', months = 0, fine = 500, color = 'green'},
        [13] = {title = 'Ulovlig u-vending', class = 'Overtrædelse', id = 'P.C. 9013', months = 0, fine = 75, color = 'green'},
        [14] = {title = 'Ulovlig overhaling', class = 'Overtrædelse', id = 'P.C. 9014', months = 0, fine = 300, color = 'green'},
        [15] = {title = 'Ulovlig sving', class = 'Overtrædelse', id = 'P.C. 9016', months = 0, fine = 150, color = 'green'},
        [16] = {title = 'Ulovlig kørelse ved skiltning', class = 'Overtrædelse', id = 'P.C. 9017', months = 0, fine = 600, color = 'green'},
        [17] = {title = 'Ulovlig Parkering', class = 'Overtrædelse', id = 'P.C. 9018', months = 0, fine = 300, color = 'green'},
        [18] = {title = 'Kørelse uden lys', class = 'Overtrædelse', id = 'P.C. 9020', months = 0, fine = 300, color = 'green'},
        [19] = {title = 'Gade ras, class = 'Forbrydelse', id = 'P.C. 9021', months = 15, fine = 1500, color = 'green'},
        [20] = {title = 'Flyver uden licens', class = 'Forbrydelse', id = 'P.C. 9022', months = 10, fine = 1700, color = 'orange'},
        [21] = {title = 'Ulovlig køretøj', class = 'Overtrædelse', id = 'P.C. 9023', months = 0, fine = 1800, color = 'green'},
        [22] = {title = 'Håndholdt telefon under kørelse', class = 'Overtrædelse', id = 'P.C. 9023', months = 0, fine = 600, color = 'green'},
    },
    [10] = {
        [1] = {title = 'Jagt I ulovlig områder', class = 'Overtrædelse', id = 'P.C. 10001', months = 0, fine = 1100, color = 'green'},
        [2] = {title = 'Jagt uden license', class = 'Overtrædelse', id = 'P.C. 10002', months = 0, fine = 1150, color = 'green'},
        [3] = {title = 'Dyremishandling', class = 'Forbrydelse', id = 'P.C. 10003', months = 15, fine = 1650, color = 'orange'},
        [4] = {title = 'Jagt med et ikke godkendt jagt gevær', class = 'Forbrydelse', id = 'P.C. 10004', months = 10, fine = 1300, color = 'orange'},
        [5] = {title = 'Jager uden for jage timerne', class = 'Overtrædelse', id = 'P.C. 10005', months = 0, fine = 1150, color = 'green'},
    }
}

Config.AllowedJobs = {}
for index, value in pairs(Config.PoliceJobs) do
    Config.AllowedJobs[index] = value
end
for index, value in pairs(Config.AmbulanceJobs) do
    Config.AllowedJobs[index] = value
end
for index, value in pairs(Config.DojJobs) do
    Config.AllowedJobs[index] = value
end

Config.ColorNames = {
    [0] = "Metallic Black",
    [1] = "Metallic Graphite Black",
    [2] = "Metallic Black Steel",
    [3] = "Metallic Dark Silver",
    [4] = "Metallic Silver",
    [5] = "Metallic Blue Silver",
    [6] = "Metallic Steel Gray",
    [7] = "Metallic Shadow Silver",
    [8] = "Metallic Stone Silver",
    [9] = "Metallic Midnight Silver",
    [10] = "Metallic Gun Metal",
    [11] = "Metallic Anthracite Grey",
    [12] = "Matte Black",
    [13] = "Matte Gray",
    [14] = "Matte Light Grey",
    [15] = "Util Black",
    [16] = "Util Black Poly",
    [17] = "Util Dark silver",
    [18] = "Util Silver",
    [19] = "Util Gun Metal",
    [20] = "Util Shadow Silver",
    [21] = "Worn Black",
    [22] = "Worn Graphite",
    [23] = "Worn Silver Grey",
    [24] = "Worn Silver",
    [25] = "Worn Blue Silver",
    [26] = "Worn Shadow Silver",
    [27] = "Metallic Red",
    [28] = "Metallic Torino Red",
    [29] = "Metallic Formula Red",
    [30] = "Metallic Blaze Red",
    [31] = "Metallic Graceful Red",
    [32] = "Metallic Garnet Red",
    [33] = "Metallic Desert Red",
    [34] = "Metallic Cabernet Red",
    [35] = "Metallic Candy Red",
    [36] = "Metallic Sunrise Orange",
    [37] = "Metallic Classic Gold",
    [38] = "Metallic Orange",
    [39] = "Matte Red",
    [40] = "Matte Dark Red",
    [41] = "Matte Orange",
    [42] = "Matte Yellow",
    [43] = "Util Red",
    [44] = "Util Bright Red",
    [45] = "Util Garnet Red",
    [46] = "Worn Red",
    [47] = "Worn Golden Red",
    [48] = "Worn Dark Red",
    [49] = "Metallic Dark Green",
    [50] = "Metallic Racing Green",
    [51] = "Metallic Sea Green",
    [52] = "Metallic Olive Green",
    [53] = "Metallic Green",
    [54] = "Metallic Gasoline Blue Green",
    [55] = "Matte Lime Green",
    [56] = "Util Dark Green",
    [57] = "Util Green",
    [58] = "Worn Dark Green",
    [59] = "Worn Green",
    [60] = "Worn Sea Wash",
    [61] = "Metallic Midnight Blue",
    [62] = "Metallic Dark Blue",
    [63] = "Metallic Saxony Blue",
    [64] = "Metallic Blue",
    [65] = "Metallic Mariner Blue",
    [66] = "Metallic Harbor Blue",
    [67] = "Metallic Diamond Blue",
    [68] = "Metallic Surf Blue",
    [69] = "Metallic Nautical Blue",
    [70] = "Metallic Bright Blue",
    [71] = "Metallic Purple Blue",
    [72] = "Metallic Spinnaker Blue",
    [73] = "Metallic Ultra Blue",
    [74] = "Metallic Bright Blue",
    [75] = "Util Dark Blue",
    [76] = "Util Midnight Blue",
    [77] = "Util Blue",
    [78] = "Util Sea Foam Blue",
    [79] = "Uil Lightning blue",
    [80] = "Util Maui Blue Poly",
    [81] = "Util Bright Blue",
    [82] = "Matte Dark Blue",
    [83] = "Matte Blue",
    [84] = "Matte Midnight Blue",
    [85] = "Worn Dark blue",
    [86] = "Worn Blue",
    [87] = "Worn Light blue",
    [88] = "Metallic Taxi Yellow",
    [89] = "Metallic Race Yellow",
    [90] = "Metallic Bronze",
    [91] = "Metallic Yellow Bird",
    [92] = "Metallic Lime",
    [93] = "Metallic Champagne",
    [94] = "Metallic Pueblo Beige",
    [95] = "Metallic Dark Ivory",
    [96] = "Metallic Choco Brown",
    [97] = "Metallic Golden Brown",
    [98] = "Metallic Light Brown",
    [99] = "Metallic Straw Beige",
    [100] = "Metallic Moss Brown",
    [101] = "Metallic Biston Brown",
    [102] = "Metallic Beechwood",
    [103] = "Metallic Dark Beechwood",
    [104] = "Metallic Choco Orange",
    [105] = "Metallic Beach Sand",
    [106] = "Metallic Sun Bleeched Sand",
    [107] = "Metallic Cream",
    [108] = "Util Brown",
    [109] = "Util Medium Brown",
    [110] = "Util Light Brown",
    [111] = "Metallic White",
    [112] = "Metallic Frost White",
    [113] = "Worn Honey Beige",
    [114] = "Worn Brown",
    [115] = "Worn Dark Brown",
    [116] = "Worn straw beige",
    [117] = "Brushed Steel",
    [118] = "Brushed Black steel",
    [119] = "Brushed Aluminium",
    [120] = "Chrome",
    [121] = "Worn Off White",
    [122] = "Util Off White",
    [123] = "Worn Orange",
    [124] = "Worn Light Orange",
    [125] = "Metallic Securicor Green",
    [126] = "Worn Taxi Yellow",
    [127] = "police car blue",
    [128] = "Matte Green",
    [129] = "Matte Brown",
    [130] = "Worn Orange",
    [131] = "Matte White",
    [132] = "Worn White",
    [133] = "Worn Olive Army Green",
    [134] = "Pure White",
    [135] = "Hot Pink",
    [136] = "Salmon pink",
    [137] = "Metallic Vermillion Pink",
    [138] = "Orange",
    [139] = "Green",
    [140] = "Blue",
    [141] = "Mettalic Black Blue",
    [142] = "Metallic Black Purple",
    [143] = "Metallic Black Red",
    [144] = "Hunter Green",
    [145] = "Metallic Purple",
    [146] = "Metaillic V Dark Blue",
    [147] = "MODSHOP BLACK1",
    [148] = "Matte Purple",
    [149] = "Matte Dark Purple",
    [150] = "Metallic Lava Red",
    [151] = "Matte Forest Green",
    [152] = "Matte Olive Drab",
    [153] = "Matte Desert Brown",
    [154] = "Matte Desert Tan",
    [155] = "Matte Foilage Green",
    [156] = "DEFAULT ALLOY COLOR",
    [157] = "Epsilon Blue",
    [158] = "Unknown",
}

Config.ColorInformation = {
    [0] = "black",
    [1] = "black",
    [2] = "black",
    [3] = "darksilver",
    [4] = "silver",
    [5] = "bluesilver",
    [6] = "silver",
    [7] = "darksilver",
    [8] = "silver",
    [9] = "bluesilver",
    [10] = "darksilver",
    [11] = "darksilver",
    [12] = "matteblack",
    [13] = "gray",
    [14] = "lightgray",
    [15] = "black",
    [16] = "black",
    [17] = "darksilver",
    [18] = "silver",
    [19] = "utilgunmetal",
    [20] = "silver",
    [21] = "black",
    [22] = "black",
    [23] = "darksilver",
    [24] = "silver",
    [25] = "bluesilver",
    [26] = "darksilver",
    [27] = "red",
    [28] = "torinored",
    [29] = "formulared",
    [30] = "blazered",
    [31] = "gracefulred",
    [32] = "garnetred",
    [33] = "desertred",
    [34] = "cabernetred",
    [35] = "candyred",
    [36] = "orange",
    [37] = "gold",
    [38] = "orange",
    [39] = "red",
    [40] = "mattedarkred",
    [41] = "orange",
    [42] = "matteyellow",
    [43] = "red",
    [44] = "brightred",
    [45] = "garnetred",
    [46] = "red",
    [47] = "red",
    [48] = "darkred",
    [49] = "darkgreen",
    [50] = "racingreen",
    [51] = "seagreen",
    [52] = "olivegreen",
    [53] = "green",
    [54] = "gasolinebluegreen",
    [55] = "mattelimegreen",
    [56] = "darkgreen",
    [57] = "green",
    [58] = "darkgreen",
    [59] = "green",
    [60] = "seawash",
    [61] = "midnightblue",
    [62] = "darkblue",
    [63] = "saxonyblue",
    [64] = "blue",
    [65] = "blue",
    [66] = "blue",
    [67] = "diamondblue",
    [68] = "blue",
    [69] = "blue",
    [70] = "brightblue",
    [71] = "purpleblue",
    [72] = "blue",
    [73] = "ultrablue",
    [74] = "brightblue",
    [75] = "darkblue",
    [76] = "midnightblue",
    [77] = "blue",
    [78] = "blue",
    [79] = "lightningblue",
    [80] = "blue",
    [81] = "brightblue",
    [82] = "mattedarkblue",
    [83] = "matteblue",
    [84] = "matteblue",
    [85] = "darkblue",
    [86] = "blue",
    [87] = "lightningblue",
    [88] = "yellow",
    [89] = "yellow",
    [90] = "bronze",
    [91] = "yellow",
    [92] = "lime",
    [93] = "champagne",
    [94] = "beige",
    [95] = "darkivory",
    [96] = "brown",
    [97] = "brown",
    [98] = "lightbrown",
    [99] = "beige",
    [100] = "brown",
    [101] = "brown",
    [102] = "beechwood",
    [103] = "beechwood",
    [104] = "chocoorange",
    [105] = "yellow",
    [106] = "yellow",
    [107] = "cream",
    [108] = "brown",
    [109] = "brown",
    [110] = "brown",
    [111] = "white",
    [112] = "white",
    [113] = "beige",
    [114] = "brown",
    [115] = "brown",
    [116] = "beige",
    [117] = "steel",
    [118] = "blacksteel",
    [119] = "aluminium",
    [120] = "chrome",
    [121] = "wornwhite",
    [122] = "offwhite",
    [123] = "orange",
    [124] = "lightorange",
    [125] = "green",
    [126] = "yellow",
    [127] = "blue",
    [128] = "green",
    [129] = "brown",
    [130] = "orange",
    [131] = "white",
    [132] = "white",
    [133] = "darkgreen",
    [134] = "white",
    [135] = "pink",
    [136] = "pink",
    [137] = "pink",
    [138] = "orange",
    [139] = "green",
    [140] = "blue",
    [141] = "blackblue",
    [142] = "blackpurple",
    [143] = "blackred",
    [144] = "darkgreen",
    [145] = "purple",
    [146] = "darkblue",
    [147] = "black",
    [148] = "purple",
    [149] = "darkpurple",
    [150] = "red",
    [151] = "darkgreen",
    [152] = "olivedrab",
    [153] = "brown",
    [154] = "tan",
    [155] = "green",
    [156] = "silver",
    [157] = "blue",
    [158] = "black",
}

Config.ClassList = {
    [0] = "Compact",
    [1] = "Sedan",
    [2] = "SUV",
    [3] = "Coupe",
    [4] = "Muscle",
    [5] = "Sport Classic",
    [6] = "Sport",
    [7] = "Super",
    [8] = "Motorbike",
    [9] = "Off-Road",
    [10] = "Industrial",
    [11] = "Utility",
    [12] = "Van",
    [13] = "Bike",
    [14] = "Boat",
    [15] = "Helicopter",
    [16] = "Plane",
    [17] = "Service",
    [18] = "Emergency",
    [19] = "Military",
    [20] = "Commercial",
    [21] = "Train"
}

function GetJobType(job)
	if Config.PoliceJobs[job] then
		return 'police'
	elseif Config.AmbulanceJobs[job] then
		return 'ambulance'
	elseif Config.DojJobs[job] then
		return 'doj'
	else
		return nil
	end
end
